variables:
  testResultDirectory: 'artifacts/TestResults'

pool:
  vmImage: VS2017-Win2016

steps:
- powershell: ./build -CodecovToken $(Codecov.Token)
  displayName: Cake Build

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(testResultDirectory)/TestResults.trx'

- task: PublishCodeCoverageResults@1
  displayName: Publish Test Coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(testResultDirectory)/TestCoverage.Cobertura.xml'

- task: CopyFiles@2
  displayName: Copy Test Artifacts
  inputs:
    sourceFolder: '$(testResultDirectory)'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/TestResults'

- task: PublishBuildArtifacts@1
  displayName: Publish Test Artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/TestResults'
    artifactType: container
    artifactName: Test Results

- task: CopyFiles@2
  displayName: Copy Package Artifacts
  inputs:
    sourceFolder: artifacts/Packages
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Packages'

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Packages'
    artifactType: container
    artifactName: Packages