pool:
  vmImage: VS2017-Win2016

steps:
- powershell: ./build -CodecovToken $(Codecov.Token)
  displayName: Cake Build

- task: CopyFiles@2
  displayName: Copy Artifacts
  inputs:
    sourceFolder: 'artifacts'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/TestResults/TestResults.trx'

- task: PublishCodeCoverageResults@1
  displayName: Publish Test Coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/TestResults/TestCoverage.Cobertura.xml'
    reportDirectory: '$(Build.ArtifactStagingDirectory)/TestCoverageReport'

- task: PublishBuildArtifacts@1
  displayName: Publish Test Artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/TestResults'
    artifactType: container
    artifactName: Test Results

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Packages'
    artifactType: container
    artifactName: Packages