pool:
  vmImage: VS2017-Win2016

steps:
- powershell: ./build >
    -ArtifactDirectory $(Build.ArtifactStagingDirectory) >
    -CoverallsToken $(Coveralls.Token)

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: $(Build.ArtifactStagingDirectory)/*.trx