pool:
  vmImage: VS2017-Win2016

steps:
- powershell: ./build
    -ArtifactDirectory $(Build.ArtifactStagingDirectory)
    -CoverallsToken $(Coveralls.Token)

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: $(Build.ArtifactStagingDirectory)\TestResults\*.trx

- task: PublishBuildArtifacts@1
  displayName: Publish Test Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\TestResults
    artifactType: container
    artifactName: TestResults