pool:
  vmImage: 'VS2017-Win2016'

steps:
- powershell: ./build
  env:
    COVERALLS_TOKEN: $(Coveralls.Token)

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: 'artifacts/*.trx'