pool:
  vmImage: VS2017-Win2016

steps:
- powershell: ./build -CoverallsToken $(Coveralls.Token)
  displayName: Cake Build

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: artifacts/TestResults/*.trx

- task: CopyFiles@2
  displayName: Copy Test Artifacts
  inputs:
    sourceFolder: artifacts/TestResults
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/TestResults

- task: PublishBuildArtifacts@1
  displayName: Publish Test Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/TestResults
    artifactType: container
    artifactName: TestResults